
## Executive Summary {-}

The purpose of this Watershed Connectivity Restoration Plan (WCRP) is to advance Takla Nation’s efforts to restore and strengthen connectivity for migratory salmonids and the cultural, ceremonial, and livelihood values they provide. Specifically, this WCRP focuses on habitat connectivity for Chinook Salmon (*Oncorhynchus tschawystcha*), Coho Salmon (*O. kisutch*), Sockeye Salmon (*O. nerka*), and steelhead (*O. mykiss*), herein referred to as Pacific salmon and steelhead, in the traditional unceded territory of the Takla Nation. This includes those portions of Takla Nation territory that support anandromous salmon: the Driftwood River, Takla Lake, Middle Skeena, Upper Skeena and Sustut River watersheds and portions of the Middle River watershed.  

This plan informs efforts to close knowledge gaps and plan and prioritize field assessments and restoration. Local data and knowledge are combined with connectivity modelling to estimate current connectivity status and identify structures that potentially block the most habitat. This informs the prioritization of field assessments to close the most significant knowledge gaps efficiently. Information from field assessments of barrier status and habitat condition are incorporated into the model, improving understanding of which barriers block the most habitat, and informing restoration prioritization. As knowledge gaps are closed and barriers are addressed, this plan will be revised to summarize progress and provide updated estimates of connectivity status and the status and relative importance of remaining structures. 

In the Driftwood River, Takla Lake, Middle River, Middle Skeena, Upper Skeena and Sustut River watersheds, 5,292 km of Pacific salmon and steelhead habitat are currently connected to the ocean and 198 km are disconnected from it. This means that 96% of the 5,490 km of total habitat is connected. 

In the Driftwood River, Takla Lake, Middle River, Middle Skeena, Upper Skeena and Sustut River watersheds, 73 structures potentially disconnect Pacific salmon and steelhead habitat. Of these, 1 is identified as barriers in need of rehabilitation (priority barriers), 0 are identified as barriers that do not warrant rehabilitation (non-actionable), and 72 require further field assessment. 


![Map of Pacific salmon and steelhead habitat and structures that are confirmed or potential barriers to fish passage in the Driftwood River, Takla Lake, Middle River, Middle Skeena, Upper Skeena, and Sustut River watersheds as of May 2026. Structure data were obtained from BCFishPass and the Canadian Aquatic Barriers Database (aquaticbarriers.ca). The accessibility model represents areas of the watershed that one or more Pacific salmon and steelhead species could access naturally in the absence of anthropogenic barriers. The habitat model represents the subset of accessible waterbodies that may be used by one or more Pacific salmon and steelhead species for spawning and/or rearing. Available local knowledge and data were incorporated and overruled habitat model results. Thick red lines represent habitat considered to be fully disconnected (upstream of barriers or unassessed structures).](content/images/Fig_1_Map_ModelOutput.png){#fig-modeloutput}


![Habitat Accumulation Curve (HAC) showing structures in the Driftwood River, Takla Lake, Middle River, Middle Skeena, Upper Skeena, and Sustut River watersheds as of May 2026. Structures are ranked based on how much (km) habitat for Pacific salmon and steelhead is upstream. The primary y-axis represents the cumulative amount of potential habitat gain (km). The secondary y-axis represents the percentage of the total Pacific salmon and steelhead habitat that would be connected if each structure were passable. Sets of structures are indicated by a grey line below the curve, indicating that gains from addressing the downstream structure alone would be less than the combined gains from addressing all structures in the set. Habitat upstream of unassessed structures is considered disconnected until field assessments are completed. Structures that were excluded as passable are not shown.](content/images/Fig2_HAC_new.png){#fig-HAC}


This WCRP was initiated in 2025, with the majority of project scoping and planning taking place in early 2026. Barrier assessment work has been completed in some portions of Takla Nation territory that overlap with Early Stuart Sockeye Salmon runs as part of a separate collaborative process known as Tuzist’ol T’ah and its associated WCRP (see [Tuzist’ol T’ah WCRP](https://tuzistoltah-wcrp.netlify.app/)). Additional field work specifically targeting the Takla WCRP is scheduled to occur in summer/fall 2026. 