# Appendix A – Status of Structures Assessed in the Field {-}

## Non-Actionable Barriers
No non-actionable barriers were identified through the implementation of this WCRP as of May 2026.  

## Data-deficient Barriers {-}

```{r table1, echo = FALSE, results = 'asis'}
#| label: tbl8
#| tbl-cap: "Table 8: Structures in Driftwood River, Takla Lake, Middle River, Middle Skeena, Upper Skeena and Sustut River watersheds that have been assessed for fish passage for Pacific salmon and steelhead as of May 2026, but either require an additional in-depth fish-passage assessment to confirm the passability status or a habitat assessment to confirm upstream habitat values. "
#| warning: false
#| echo: false
source("Rscripts/table_formatting.R")
library("flextable")

data <- read.csv("data/tbl8.csv", check.names=FALSE)
ft <- flextable(data)
ft <- format_flextable(ft)
ft
```
## Excluded Structures {-}

```{r table1, echo = FALSE, results = 'asis'}
#| label: tb9
#| tbl-cap: "Table 9: Structures in Driftwood River, Takla Lake, Middle River, Middle Skeena, Upper Skeena and Sustut River watersheds that are excluded from further consideration in subsequent ranking and work planning because the structure is not present, is confirmed passable (e.g., bridge), or has no habitat upstream for Pacific salmon and steelhead."
#| warning: false
#| echo: false
source("Rscripts/table_formatting.R")
library("flextable")

data <- read.csv("data/tbl9.csv", check.names=FALSE)
ft <- flextable(data)
ft <- format_flextable(ft)
ft
```



