# Progress Reporting {-}

## Progress Reporting {-}
This WCRP was initiated in 2025, with the majority of project scoping and planning taking place in early 2026. Triple Creek was identified as a priority barrier by Takla Nation based on a combination of traditional knowledge and past field work that included both a barrier assessment and confirmation of habitat quality upstream of this barrier. Twelve structures were excluded from further consideration based on a combination of local knowledge and satellite imagery review. Barrier assessment work has been completed in some portions of Takla Nation territory that overlap with Early Stuart Sockeye Salmon runs as part of a separate collaborative process known as Tuzist’ol T’ah and its associated WCRP (see [Tuzist’ol T’ah WCRP](https://tuzistoltah-wcrp.netlify.app/)), resulting in 8 structures being confirmed as barriers and requiring further field assessment to determine habitat values, and 17 structures being excluded from further consideration due to being passable, no structure being present, or no upstream habitat. Additional field work specifically targeting the Takla WCRP is scheduled to occur in summer/fall 2026. 

## Rehabilitated Barriers {-}
No barriers were rehabilitated through the implementation of this WCRP as of May 2026. 

## Annual Progress Report {-}
Since April 2025, the following actions were completed: 

Satellite imagery review of crossings within the geographic scope was completed and structure statuses updated accordingly (i.e., removed where no structure is present, excluded as passable where clearspan bridge is visibly present).  

A series of WCRP scoping workshops were held to determine focal species and geographic scope of the WCRP, develop connectivity goals, and complete a tributary-by-tributary review to provide corrections to the connectivity model based on local and traditional knowledge, where available.  

Existing barrier assessment data from past field work, including work completed for the Tuzist’ol T’ah WCRP in 2025, was incorporated into the connectivity model. 

The connectivity model was updated based on the above actions, and outputs were incorporated into this WCRP. 
